export enum MailTemplateEnum {
  USER_REGISTER = '01',
  USER_REGISTERED = '02',
  ASYNC_JOB_DONE = '03',
  FILE_LIMIT_REACHED = '04',
  WORKSPACE_INVITE = '05',
  VERSION_CONFIRMED = '06',
  DESIGN_DELETED = '07',
  WORKSPACE_INVITE_NO_ACCOUNT = '08',
}
